services:
  postgres:
    image: postgres:18-alpine
    container_name: bei_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exchange
    ports:
      - "5432:5432"
    volumes:
      - bei_pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d exchange"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  bei_pgdata:
    driver: local
